# Generated by Django 4.2.30 on 2026-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicslot',
            name='course',
        ),
        migrations.AddField(
            model_name='academicslot',
            name='subject',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
