# Generated by Django 4.2.30 on 2026-04-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_academicslot_course_academicslot_subject_and_more'),
        ('users', '0003_remove_user_major_remove_user_semester_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
