# Generated by Django 4.2.30 on 2026-04-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_remove_academicslot_course_academicslot_subject_and_more'),
        ('users', '0002_user_major_user_profile_picture_user_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_slots',
            field=models.ManyToManyField(blank=True, related_name='users_saved', to='university.academicslot'),
        ),
    ]
