# Generated by Django 4.2.30 on 2026-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('UNIVERSITY', 'University'), ('WORK', 'Work')], default='UNIVERSITY', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
