# Generated by Django 4.2.30 on 2026-04-21 00:16

import backend.apps.rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_category_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=backend.apps.rooms.models.generate_room_code, max_length=6, unique=True),
        ),
    ]
