# Generated by Django 4.2.30 on 2026-04-16 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('rooms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleentry',
            unique_together={('room', 'day', 'time_slot')},
        ),
    ]
