# Generated by Django 4.2.30 on 2026-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
