# Generated by Django 4.2.30 on 2026-04-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('schedule', '0003_scheduleentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='academic_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='university.academicslot'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='entry_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic'), ('NOTE', 'Note')], default='NOTE', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
